rainforest/config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  end
end

rainforest/app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}
  has_many :reviews
  has_many :users, through: :reviews


  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

rainforest/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

rainforest/app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :products, through: :reviews
  has_secure_password
  validates :name, presence: true
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
def ensure_logged_in
  unless current_user
    flash[:alert] = "Please log in"
    redirect_to new_session_path
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
  end
end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
  end
end

def destroy
  @product = Product.find(params[:id])
  @product.destroy
  redirect_to products_path
end

  private
  def product_params
  params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :ensure_logged_in, only: [:create, :destroy]
  before_action :load_product

  def show
    @review = Review.find(params[:id])
  end


  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to products_path, notice: 'Review created successfully'
    else
      render 'products/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

private
def review_params
  params.require(:review).permit(:comment, :product_id)
end

def load_product
  @product = Product.find(params[:product_id])
end
end

rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "Logged in!"
    else
      render "new"
  end

  def destroy
    session[:user_id] = nil
       redirect_to products_url, notice: "Logged out!"
  end
end

rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.Save
      redirect_to products_url, notice: "Signed up!"
    else
      render "new"

  end
end

private
  def user_names
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest/app/helpers/users_helper.rb
module UsersHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  
<%= yield %>
<p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
</body>
</html>

rainforest/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :description %> <br />
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.label :price_in_cents %><br />
      <%= f.number_field :price_in_cents %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

    <div id= "error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      </ul>
    </div>
<% end %>
<% end %>

rainforest/app/views/products/edit.html.erb
<h1>Products#edit</h1>
<h1></h1>
<%= render 'form' %>

rainforest/app/views/products/index.html.erb
<h1>Products#index</h1>
<% @products.each do |product|%>
<p><%=product.name%> <%= product.description %> <%= product.formatted_price %>
</p>

<% end %>

rainforest/app/views/products/new.html.erb
<h1>New product</h1>
<%= render 'form' %>

<%= link_to 'Back', products_path %>
<%= form_for @products do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>

<p>Find me in app/views/products/new.html.erb</p>

rainforest/app/views/products/show.html.erb
<h1>Products</h1>
<p>
<%=@product.name%> <%= @product.description %> <%= @product.formatted_price %></p>

<h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

rainforest/app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

rainforest/app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

rainforest/app/views/reviews/show.html.erb
<% if current_user %>
  <h4>New Review</h4>

  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

rainforest/app/views/users/new.html.erb
<div class="field">
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</div>